[#10] 비동기 쿠폰 발급 기능 구현
f-lab-edu/off-coupon pull request #12
Opened 2024-03-23 11:55 UTC by codesejin

관련 Issue : #10 

# 쿠폰 발급 비동기 API

2024-03-23 14:24 UTC, f-lab-maverick requested changes
고생하셨습니다~ 리뷰 확인 후 다시 요청해주세요!

2024-03-23 14:24 UTC, f-lab-maverick commented on load-test/docker-compose.yml
docker compose를 적용하려고 하신건가요? 어떤것을 적용하려고 시도하신건가요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/config/security/configs/SecurityConfig.java
> +                                        "/api/v1/sse/**",
테스트용으로 열어둔 권한은 잊지말고 이후에 꼭 권한처리해주세요~

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/controller/HomeController.java
> +    @GetMapping("/main")
`Controller` 레벨에 `RequestMapping`으로 `/`를,
메소드 레벨에 추가적인 매핑을 `/`, `/main`으로 해둔다면 중첩되어서 요청 URL이 `//`, `//main`이 됩니다.

Spring에서 이런 부분을 어느정도 처리해서 괜찮겠지만, 논리적으로 이슈가 생기는 부분이니 `Controller` 레벨에서 `RequestMapping`을 제거해주시는건 어떠실까요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/ConnectionPoolInterface.java
커넥션풀과 관련된 로직을 추상화하려고 한 시도로 보이네요.
인터페이스로 분리하여서 어떤 장점을 가져가려고 하셨나요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
Socket 방식이 아닌 SSE를 선택한 이유가 있을 것으로 보입니다~ SSE와 소켓의 장단점을 비교해보셨을텐데 어떤 이유에서 SSE를 고르셨나요?
또한, 직접 폴링 / 롱폴링등의 기법을 사용해볼 수도 있었을 것으로 보이는데 어떤 기능들과 비교해보셨나요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +
이미 Session이 있는 경우에 대한 처리는 어떻게되나요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    }
Session이 조회되지 않는 경우에는 어떻게 될까요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
유저의 세션을 특정 서버에 보관한다면, 서버가 다운되었을 때 장애상황에 대처할 수 있는 방법이 있을까요?

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    /**
Rabbit MQ에서 데이터를 들고오는것부터 트랜잭션이 시작할 이유가 있을까요?

트랜잭션의 범위는 최소한으로 줄여야 undo영역에 데이터가 많이 쌓이는 것을 방지할 수 있고, 성능과 데이터이슈에도 유리합니다. 또한 Queue에 메세지가 없는데 매번 트랜잭션을 시작할 필요도 없겠네요~

Queue에서 데이터를 들고오는 부분은 트랜잭션과 연결될 이유가 없으니 트랜잭션 외부에서 진행하도록 해주세요~

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    public void consumeCouponIssueMessage() throws IOException {
`IOException`과 같은 checked exception을 메소드 외부로 throw하게 되면 꽤나 이슈가 있습니다.
1. IOException이 발생할 경우 트랜잭션이 롤백되는 조건에 해당할까요?
2. 이 메서드를 사용하는 모든 메서드에서 `try-catch`를 사용해야 하지 않을까요?

이러한 이슈가 있기 때문에 Exception wrapping & Rethrowing 기법을 많이 사용합니다. 이 키워드로 한번 찾아보세요~

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/util/CouponRabbitMQUtils.java
> +    public static final String EXCHANGE_NAME = "coupon-issue.exchange";
이 클래스틑 아직까지는 상수만 담아두는 역할을 하고있네요. 별도 유틸 메서드가 없다면 네이밍을 상수 클래스라는걸 알 수 있게 변경해주세요.

추가적으로, 유틸클래스의 경우 생성자를 없애는것도 좋지만 lombok에서 제공해주는 [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)를 사용하실 수도 있습니다. 꽤 여러가지 기능을 해주니 한번 문서를 읽어보세요~

2024-03-23 14:24 UTC, f-lab-maverick commented on src/main/resources/application.properties
> +spring.rabbitmq.password=${RABBITMQ_PASSWORD}
비밀정도 숨기기 좋습니다 👍

2024-03-23 14:24 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/repository/MemberRepositoryTest.java
> +        setupUtils = new SetupUtils();
이렇게 인스턴스화를 하는 대상은 유틸 클래스라고 보기는 어렵네요.
유틸리티성 클래스의 경우 상태가 없어야 합니다.

특정 값을 세팅해주는게 목표라면 `Initializer`, `Factory` 등의 네이밍을 사용해보시는건 어떨까요?

2024-03-24 07:27 UTC, codesejin commented on load-test/docker-compose.yml
locus라는 부하테스트 툴을 통해 동기랑 비동기 API 테스트하려고 했습니다!

2024-03-24 07:32 UTC, codesejin commented on src/main/java/com/flab/offcoupon/controller/HomeController.java
> +    @GetMapping("/main")
넵 수정했습니다 감사합니다!

2024-03-25 06:07 UTC, codesejin reviewed
리뷰해주신 내용대로 수정했습니다..!

2024-03-25 06:07 UTC, codesejin commented on src/main/resources/application.properties
> +spring.rabbitmq.password=${RABBITMQ_PASSWORD}
감사합니다!

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    /**
메세지큐를 사용하지 않을때도 스케줄링때문에 3초마다 트랜잭션이 열릴것이라고 생각을못했네요!
알려주셔서 감사합니다! 수정했습니다!

2024-03-25 06:07 UTC, codesejin commented on src/test/java/com/flab/offcoupon/repository/MemberRepositoryTest.java
> +        setupUtils = new SetupUtils();
Initializer로 변경하겠습니다 감사합니다!

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/util/CouponRabbitMQUtils.java
> +    public static final String EXCHANGE_NAME = "coupon-issue.exchange";
@UtilityClass를 사용하면,  컴파일 시점에 생성자 private 으로 만들어 주고, 모든 메서드를 static으로 만들어 줘서 더 명시적인것 같습니다 알려주셔서 감사합니다!

상수만 있는 클래스는 Utils대신 Constants로 변경하겠습니다!

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
1. `직접 폴링` : 클라이언트가 특정 주기로 request를 날려서 이벤트를 받는 방식인데, http overhead가 많이 발생합니다. http 요청 커넥션을 맺고 끊는걸 반복하기 때문에 불필요한 네트워크 호출이 많이 발생합니다.
2. `롱 폴링` : 클라이언트가 서버로 request를 보내면 대기중이다가 서버에서 이벤트를 받으면 연결이 종료되는 방식입니다. 직접 폴링에 비해 네트워크 호출이 적기 때문에 http overhead가 적게 발생하지만, 다수의 클라이언트에게 동시 이벤트가 발생할 경우 서버 접속이 급격하기 늘어나면서 서버 부하가 발생합니다.
4. `socket` : 단일 tcp/ip를 사용하는 방식으로 클라이언트와 양방향으로 메세지를 주고받는것이 아니기 때문에 사용하지 않았습니다.
5. `sse` : 추가적으로 socket연결을 하지 않아도 기존의 http연결을 재사용해 데이터를 전송하기 때문에 별도의 프로토콜이 필요하지 않습니다. 그리고 서버에서 단방향으로 이벤트를 알려주는 것이기 때문에 sse를 사용했습니다.

이 외에도 `fcm`같은 경우에도 push 알림이 가능하고, 다양한 플랫폼에서 사용할 수 있지만 sse에 비해 실시간성이 느립니다. 이미 비동기 방식으로 일정한 시간동안 쿠폰 발급이 진행되기 때문에 여기서 더 지연시간이 발생한다면 사용자 경험이 떨어질것이라고 생각했습니다.

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
단일 서버에서 세션을 보관하는데 다운될 경우 데이터 유실이 발생합니다.
그래서 저는 redis를 활용해 session storage방식을 사용했는데, redis를 master/slave 혹은 클러스터링으로 구성해서 복제하면 장애를 예방할 수 있습니다

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +
기본적으로 Map을 사용했기 때문에  key에 동일한 session이 있을 경우 value가 대체 됩니다.
그런데 value이 경우 userSseConnection 객체를 통해 session과 커넥션풀, json으로 변형하기 위한 objectmapper가 생성되므로 , 사실상 계속 동일 session을 사용하는거랑 다름이 없습니다

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    }
Session이 조회되지 않을 경우 UserSseConnection는 null이 되고,
이상태로 메세지를 push할때 어떤 session으로 보낼지 값이 나오지 않습니다.


세션이 조회되지 않을 경우 exception 처리하는걸로 변경하겠습니다
![image](https://github.com/f-lab-edu/off-coupon/assets/101460733/491a7f0f-16d2-407e-8982-a99c10319bbf)

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    public void consumeCouponIssueMessage() throws IOException {
1. @Transactional 사용 시 아무런 옵션없이 사용한다면 기본적으로 Unchecked Exception과 Errors만 확인 후 롤백 시킵니다. IOException은 Checked Exception이기 때문에 트랜잭션 내부에 Checked Exception이 발생할 여지가 있다면 `@Transactional(rollbackFor = Exception.class)` 를 설정해줘야 합니다.
-> 리팩토링과정에서 트랜잭션을 분리했기 때문에, 트랜잭션 범위내에 IOException이 존재하지 않아서 별도로 설정하지 않겠습니다.

3. 말씀해주신것 처럼 처음 메소드에서 throws를 사용(`예외 회피`)하다보니 해당 메소드를 호출하는 상위메소드에도 예외 전파 현상이 발생합니다. 

CheckedException은 복구 불가능이기 때문에 최초 메소드에서  Exception catch -> UncheckedException으로
`Exception wrapping`을 통해 `예외 전환`을 사용하여 Exception Hadling을 하도록 변경했습니다.
<img width="913" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/c37c389b-38d8-4e31-bce2-6e98fe46cd2c">

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/ConnectionPoolInterface.java
추후에 sse가 아닌 fcm으로 기능 변경이 변경될때를 대비해서 인터페이스로 분리했습니다.
그런데 fcm은 제가 직접 구현해보진 않았지만 메소드명에서 sse와 차이가 있을것 같습니다...

2024-03-25 06:07 UTC, codesejin commented on src/main/java/com/flab/offcoupon/config/security/configs/SecurityConfig.java
> +                                        "/api/v1/sse/**",
넵 수정했습니답..!

2024-03-25 14:07 UTC, f-lab-maverick requested changes
확인하였습니다~ 리뷰 확인해주시고 다시 요청해주세요.

2024-03-25 14:07 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
현재 소스코드에서는 `private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();` 형태로 서버의 메모리 내부에 저장하고 있습니다. 별도로 redis로 저장하는 로직이 없는데 유실에 대한 대비는 따로 없으신건가요?

2024-03-25 14:07 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    public static CouponIssueMessageForQueue message;
3초마다 스케줄링이 호출된다면, 만약 로직이 3초를 넘어서는 시간동안 실행된다면 실행되는 동안 이 `message`변수가 다른 변수로 재할당 되며 버그가 날 위험성이 있습니다.

또한 `public static` 접근제어자이기 떄문에 다른 클래스에서 이 변수를 가져다쓰다가 다시 가져다쓰려고 할 때 또다른 인스턴스로 재할당되어서 다른 인스턴스가 튀어나오기도 하겠네요.

외부에서 아래처럼 이 변수를 null로 재할당하는 로직도 있어서 상당히 위험한 로직으로 보입니다.
```
totalUpdateIssuedCouponAndDeleteRequest
```


이렇게 message 변수를 참조하며 상태를 변경하는 메서드들이 정말 동시다발적으로 많이 발생한다면 굉장히 큰 버그로 다가올 수 있습니다. 동시성 이슈가 꽤나 많이 일어날 수 있는 영역이며, 별도의 동시성 제어또한 들어가있지 않아 꼭 수정이 필요한 영역으로 보입니다.

해결방법으로 애초에 public static 변수가 필요한지에 대해 고려해보면 좋을거같네요.
필요할 때 지역변수로 생성하여 만들어두고, 이후 폐기하면 되지 않을까요?


아래 메서드를 
```
@Scheduled(fixedDelay = 3000)
    public void consumeCouponIssueMessage() {
        if (existCouponIssueQueueTarget()) {
            message = (CouponIssueMessageForQueue) rabbitTemplate.receiveAndConvert(QUEUE_NAME);
            log.info("'coupon-issue.queue'에 메시지가 있습니다. message: {}", message);
            couponIssueMessageHandler.saveEachCouponIssueHistory(message);
            sseAlertSender.pushSseMessage(message.memberId(),"쿠폰이 발급 완료되었습니다. memberId : %s");
        } else {
            log.info("'coupon-issue.queue'가 비어있습니다.");
            couponIssueMessageHandler.totalUpdateIssuedCouponAndDeleteRequest(message);
        }
    }
```

이렇게 바꿀 수 있습니다.
```
@Scheduled(fixedDelay = 3000)
    public void consumeCouponIssueMessage() {
        if (existCouponIssueQueueTarget()) {
            CouponIssueMessageForQueue  message = (CouponIssueMessageForQueue) rabbitTemplate.receiveAndConvert(QUEUE_NAME);
            log.info("'coupon-issue.queue'에 메시지가 있습니다. message: {}", message);
            couponIssueMessageHandler.saveEachCouponIssueHistory(message);
            sseAlertSender.pushSseMessage(message.memberId(),"쿠폰이 발급 완료되었습니다. memberId : %s");
        } else {
            log.info("'coupon-issue.queue'가 비어있습니다.");
            couponIssueMessageHandler.totalUpdateIssuedCouponAndDeleteRequest(message);
        }
    }
```

2024-03-25 14:07 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/util/DateTimeUtils.java
> +@UtilityClass
이 어노테이션을 붙이면 메서드에서 static 키워드를 빼도 static이 붙여진것으로 인식되어 동작합니다.
다만 가독성이나 헷갈리지 않는 영역 때문에라도 static키워드는 그대로 남겨두는게 더 좋아보이네요 :)

2024-03-28 00:18 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/coupon_issue/async/consumer/CouponIssueConsumer.java
> +    public static CouponIssueMessageForQueue message;
멘토링 시간때 말씀해주신대로 스케줄링 2번하는걸로 변경했습니다!

2024-03-28 00:22 UTC, codesejin reviewed
sse관련해서 세션을 concurrentHashMap에다 저장했는데 objectmapper 로 역직렬화과정에서 트러블 이슈가 있어서 하지못했습니다. 아래 코멘트에 추가적으로 달았습니다!

2024-03-28 00:22 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
아 부분은 redis역직렬화 문제로 트러블 이슈가 있어서, 특정서버에 보관하는 걸로 대체했습니답..

2024-03-28 02:47 UTC, codesejin reviewed
PR리뷰 주신대로 반영했는데, Redis에 sse관련해서 Redis에 저장하는 부분은  ObjectMapper 에서 역직렬화할때 고려해야할 상황이 있습니답

2024-03-28 02:47 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
redis에 별도로 저장하려고 시도해봤는데 우선 이렇게 한 이유를 설명드리자면,

1. Redis에 Object를 저장하려면 `ObjectMapper`를 사용해서 Json으로 변환을 해줘야됩니다.
2. Redis에 저장하려는 객체는 UserSseConnection 타입인데, UserSseConnection 내부에 또 다른 객체가 필드로
SseEmitter, SseConnectionPool, ObjectMapper 3가지가 있습니다.
3.  ObjectMapper를 사용해서 Json으로 변형하려면  타입으로 된 필드에 getter가 있어야 가능합니다.
```
public class Jobs {
    private String jobName;
    private int salary;

    public String getJobName() {
        return jobName;
    }

    public int getSalary() {
        return salary;
    }
}
```
<img width="887" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/c0370d2c-0ab9-4bf5-91af-51864e9b6ff6">

4. 그런데  각 필드가 프레임워크또는 인터페이스 타입이라  getter사용이 불가능하고 @JsonIgnore를 사용하면  Redis에 timeout이 null되버려서 괜찮을까 고민했습니다.
```
{
  "uniqueKey": "1",
  "sseEmitter": {
    "timeout": 60000 // -> null로 됨
  },
  "connectionPoolIfs": {},  // -> null로 됨
  "objectMapper": {}  // -> null로 됨
}
```
6. 그래서 redis를 사용하지 못했습니답..

추가적으로 로직을 다시 생각해봤을때 message queue에서 받은 memberId로 알림을 전송하는거라 session이 아닌 memberId로 식별해야 할것 같다고 판단이 되어 수정했습니답

2024-03-28 13:59 UTC, f-lab-maverick reviewed
고생하셨습니다. 간단한 코멘트 남겨두었으니 확인해주세요~

2024-03-28 13:59 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/component/sse/SseAlertSender.java
> +        UserSseConnection userSseConnection = sseConnectionPool.getUniqueKey(String.valueOf(memberId));
👍

2024-03-28 13:59 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
Redis에 저장하는 DTO와 실제 비즈니스 DTO를 분리하면 해결될 이슈로 보이네요. 오늘 좀 더 자세히 살펴보며 개선해야할 점을 좀 더 피드백드리겠습니다.

1. `UserSseConnection`은 불필요한 파라미터인 `objectMapper`를 들고있습니다. 메세지를 직렬화하고 역직렬화하려는 의도로 보이는데, 이건 커넥션의 역할이 아니죠. 메세지는 <String>으로 통일하고 직렬화는 이 커넥션을 이용하는 서비스가 직접 직렬화하여 입력하도록 만들면 불필요한 변수를 줄일 수 있습니다.
2. 이 서비스에서 사용자에게 SSE를 위해 저장해야 하는 것은 사용자의 유니크 키 정도입니다. 이 커넥션을 미리 만들어놔야할 이유가 있나요? 사용자의 유니크 id정도만 따로 관리하고 이 커넥션객체는 SSE를 보낼 때 생성해서 사용해도 되지 않을까요?

2024-03-30 08:57 UTC, codesejin reviewed
수정 완료했습니다~

2024-03-30 08:57 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/sse/SseConnectionPool.java
> +    private static final Map<String, UserSseConnection> connectionPool = new ConcurrentHashMap<>();
말씀해주신대로 변경해보겠습니다 감사합니다!

또 다른 이슈사항이 있어서, 설계를 수정했습니답

-----
- 기존 설계 : RabbitMQ에서 메세지를 consume하면 바로 SSE 알람 전송 
-  변경된 설계 : RabbitMQ에서 메세지를 consume하면 Redis의 Publisher가 memberId기준으로 토픽 생성 후 메세지 전송
- SSE를 연결하고 있는 쪽에서는 Redis Subscriber로서 해당 토픽을 구독하고 있다가 메세지를 받으면 SSE 알람 전송
- 이유 : 기존 설계는 여러 was에서 sseemitter객체를 공유할 수 없었음(ConcurrentHashMap사용
- 그래서 Redis에 memberId와 SseEmitter객체를 저장하려고 했으나, SseEmitter는 통신을 담당하기 때문에 Serialize해도 재사용 못함
- 결국 Redis Pub/Sub을 사용해서 토픽을 구독중인 유저에게 SSE 알람 전송하는 방식으로 수정

2024-03-30 12:58 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2024-03-30 12:58 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/config/ObjectMapperConfig.java
> +    }
Spring Web MVC모듈을 쓰신다면 `ObjectMapper`는 이미 bean으로 등록이 되어 있습니다~ 별도로 등록하지 않아도 됩니다.

2024-03-30 21:36 UTC, codesejin commented on src/main/java/com/flab/offcoupon/config/ObjectMapperConfig.java
> +    }
알려주셔서 감사합니다!

2024-03-30 21:39 UTC, merged