Feature/query optimization
f-lab-edu/off-coupon pull request #17
Opened 2024-04-21 08:26 UTC by codesejin

2024-04-21 14:54 UTC, f-lab-maverick requested changes
고생하셨습니다. 남긴 코멘트 확인해서 답변 남기신 후 다시 리뷰요청해주세요~

2024-04-21 14:54 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +        getMonthlyStatistics(startedAt, endedAt, monthlyStatisticsList);
파라미터로 넘어간 `monthlyStatisticsList`에 값을 추가하지 말고, 통계결과를 List로 반환하게 만들어보세요. 파라미터의 상태를 바꾸는 함수나 메서드는 결과를 예측하기 어려울 뿐 아니라 상태를 바꾸는 사이드이펙트가 있는 메서드가 됩니다.

```suggestion
        List<MonthlyOrderStatistics> monthlyStatisticsList = getMonthlyStatistics(startedAt, endedAt);
```

2024-04-21 14:54 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +                });
`monthlyStatisticsList.addAll(monthlyStatistics);` 넘어온 자료구조가 Thread-safe한 자료구조인가요? 이 메서드는 Thread safe할까요?

2024-04-25 21:53 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +        getMonthlyStatistics(startedAt, endedAt, monthlyStatisticsList);
넵 반환하는걸로 변경하겠습니다 알려주셔서 감사합니다!

2024-04-26 05:39 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +                });
병렬스트림 사용으로 동시에 작업이 발생해서 데이터를 추가할 경우 ArrayList의 add(), addAll()메소드는 Thread safe하지 않습니다! 자바의 동시성 컬렉션 라이브러리인 `CopyOnWirterArrayList`로 변경하겠습니다..!

2024-04-26 17:30 UTC, f-lab-maverick requested changes
리뷰 확인 후 다시 요청해주세요~

2024-04-26 17:30 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/dto/response/MonthlyOrderStatistics.java
> +    }
생성자 파라미터로 null이 넘어와야하는 경우가 있나요? 만약 null이 넘어온다면 오류인 상황일 것으로 보이는데, 이 경우에는 명시적으로 에러를 throw해주는게 좋습니다. 이런식으로 단언문을 사용하기도 하니 참고해주세요~
```suggestion
    public MonthlyOrderStatistics(MonthlyOrderStatisticsVo vo) {
      Assert.notNull(vo, "생성자 파라미터는 null일 수 없습니다");
      ...
    }
```

2024-04-26 17:30 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +        monthlyStatisticsList.sort(Comparator.comparing(MonthlyOrderStatistics::getYearMonth));
`List.sort`는 원본 컬랙션의 순서를 변경합니다.
어떤 객체든지 상태를 변경하는 것은 동시성이슈나 버그발생을 일으킬 수 있기 떄문에 주의해야하며, 컬랙션은 여러 메서드에서 공유하는 경우가 많아 더더욱 주의해야 합니다. 이런 경우에는 원본을 아예 변경하지 않도록 컬랙션을 stream으로 복사하는 방식을 자주 사용하니 참고해주세요.

```
return monthlyStatisticsList .stream().sort(Comparator.comparing(MonthlyOrderStatistics::getYearMonth)).toList();
```

2024-04-26 17:30 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +        monthlyStatisticsList.sort(Comparator.comparing(MonthlyOrderStatistics::getYearMonth));
비슷한 예로 객체 내부에 컬랙션을 가지고 있는 경우에도 getter를 만들 때 원본 리스트가 아닌 복사본을 리턴하도록 만들기도 합니다.

```
public List<?> getFoo() {
  return List.copyOf(list);
}
```

2024-04-26 17:30 UTC, f-lab-maverick commented on src/main/resources/mapper/StatisticsMapper.xml
> +        order by YearMonth;
group by가 있더라도 MySQL은 group by한 컬럼대로 순서를 보장해주지 않죠. 명시적으로 order by를 걸어준 부분 좋습니다 👍

2024-04-26 17:30 UTC, f-lab-maverick commented on src/main/resources/mapper/StatisticsMapper.xml
> +        order by YearMonth;
SQL문은 대부분 SNAKE_CASE를 사용합니다. camelCase를 사용하지 않으니 SQL문에 대해서는 파라미터명과 쿼리문에 snake case를 사용해주세요. 왜냐하면 대부분의 DB에는 대/소문자의 구분을 하지 않도록 설정하는 옵션이 있기 때문에 camelCase를 사용하면 오타가 있어도 쿼리가 실행되는 경우가 생깁니다. 이런 경우를 방지하기 위해 어지간하면 SNAKE_CASE를 사용해주세요~

2024-04-28 03:48 UTC, codesejin commented on src/main/resources/mapper/StatisticsMapper.xml
> +        order by YearMonth;
앗 이 부분은 계속 SNAKE_CASE를 사용하지 않고 있네요.. 습관처럼 SNAKE_CASE를 사용할 수 있도록 신경쓰겠습니다!

2024-04-28 03:58 UTC, codesejin commented on src/main/resources/mapper/StatisticsMapper.xml
> +        order by YearMonth;
감사합니다~ group by한 컬럼대로 순서를 보장하지 않기 때문에 order by 사용!

2024-04-28 04:56 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/StatisticsService.java
> +        monthlyStatisticsList.sort(Comparator.comparing(MonthlyOrderStatistics::getYearMonth));
아하 stream을 사용하면 원본 객체를 복사해서 작업하기 때문에 `동시성이슈나 버그발생` 이 안일어나는군요! 알려주셔서 감사합니다..!

2024-04-28 05:00 UTC, codesejin commented on src/main/java/com/flab/offcoupon/dto/response/MonthlyOrderStatistics.java
> +    }
이 부분은 제가 조회에서 데이터 가져올때 어차피 1개월 기준으로 받아오니까 List가 아닌 객체로 받으면 되지 않을까 싶었는데요!
List가 아닌 객체로 받아오니까 `해당하는 기간 범위에 데이터가 없을때`에 객체가 Null이 되버리는 문제가 있어서 추가했었습니다!

그런데, List로 받아오면 애초에 null인 객체가 List에 추가되지 않아서 List로 반환하는걸로 했습니다.
그래서 말씀해주신 Null 체크는 없애도록 하겠습니다! 더 좋은 코드 추천해주셔서 감사합니다~!

2024-04-28 08:24 UTC, codesejin commented on src/main/resources/mapper/StatisticsMapper.xml
> +        order by YearMonth;
앗 멘토님 alias에서 SNAKE_CASE를 사용하면 반환타입의 VO 필드랑 매핑이 안되더라구요! yearMonth만 CAMEL_CASE로 적용하겠습니다!

2024-04-28 13:10 UTC, f-lab-maverick approved these changes
고생하셨습니다. 머지해주셔도 좋습니다~

2024-04-28 13:47 UTC, merged