[#19]
f-lab-edu/off-coupon pull request #21
Opened 2024-05-09 10:33 UTC by codesejin

2024-05-10 12:21 UTC, f-lab-maverick requested changes
객체지향 + 도메인지향을 적절하게 잘 적용하셨네요~
피드백 수정 후 다시 리뷰요청해주세요.

2024-05-10 12:21 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/model/Positive.java
👍

2024-05-10 12:21 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/cache/CouponCacheServiceImpl.java
> +    @Cacheable(key = "#couponId",value = "coupon")
캐시 기능이 있는 어노테이션은 `@Cacheable`만 존재하지 않습니다~ 다양한 캐시 어노테이션을 찾아보시고, 그 어노테이션들의 캐시 전략에 대해서 한번 찾아보시겠어요?

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/AbstractIntegrationContainerBaseTest.java
> +@ActiveProfiles("local")
상당히 많은 어노테이션을 사용하셨네요. 각각의 어노테이션이 어떤 역할을 할까요? 설명할 수 있을까요?

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/AbstractIntegrationContainerBaseTest.java
통합테스트를 할 때 어떤 전략을 사용한건지 주석으로 적어주시면 이해하기 좋을 것으로 보입니다~

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/entity/OrderCouponTest.java
> +    }
테스트의 명칭은 행위와 조건이 명확해야 합니다.
이 테스트가 실패한다면 다른 개발자가 이 테스트의 이름만 보고 어떤 정합성이 깨진 것인지 알 수 있을까요?

길어도 좋으니 아래와 같은 이름이 실패했을 때 알아보기 더 쉽습니다.
"0보다 큰 숫자로 AppliedCouponInfo를 생성하면 성공적으로 생성된다"

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/entity/OrderDetailTest.java
> +}
생성 성공케이스 뿐만 아니라, 실패케이스(생성자 validation이 있다면)가 있다면 꼭 작성해주세요. 단위테스트는 성공 / 실패 / 엣지케이스가 포함되어야 합니다.

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @CsvSource(value = {"10000, 0", "50000, 0"})
👍  JUnit 기능을 잘 사용하셨네요

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @DisplayName("[SUCCESS] 세일 가격이 0보다 클 경우 세일 가격 반환")
실패케이스로 세일가격이 0보다 작은 값이 들어올 경우가 있으면 되겠네요~

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @DisplayName("[SUCCESS] 상품 가격에 수량을 곱한 값을 반환")
테스트는 이 메서드가 어떤 역할을 하는지보다는 이 테스트가 어떤 비즈니스로직을 수행하는가를 적어주시는게 명확합니다. 행위와 성공조건이 포함된 테스트이름으로 다시 작성한다면
`총 가격은 상품 가격과 개수를 곱한 값과 일치한다` 와 같은 형태로 테스트를 생성해야 추후 이 테스트의 목적을 알 수 있습니다.

2024-05-10 12:21 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/domain/redis/EventRedisEntityTest.java
> +            assertEquals(dailyIssueEndTime, eventRedisEntity.dailyIssueEndTime());
이렇게 여러가지의 테스트 검증을 할 때에는 위쪽 assert가 실패하면 아래쪽 assert는 실행하지도 못하고 종료되어 모든 단언을 수행하지 않고 그대로 실패해서 몇개의 단언문이 실패했는지 알 수 없습니다. 이것도 하나의 팁이라면 이렇게 여러가지를 검증할 때에는 `assertAll`을 사용하면 어떤 단언문이 성공했고, 어떤 단언문이 실패했는지 개별적으로 수행하기 때문에 알기 좋습니다.

2024-05-16 00:22 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/cache/CouponCacheServiceImpl.java
> +    @Cacheable(key = "#couponId",value = "coupon")
- `@Cacheable` : 캐시를 저장 / 조회하기 위한 어노테이션  - `Look-aside (Lazy-loading)`
  - 캐시에 데이터가 없을 경우에는 DB에서 조회해서 캐시에 데이터를 추가하고, 캐시에 데이터가 있으면 캐시 데이터를 반환
  - Look-aside 캐싱 전략에서는 애플리케이션이 먼저 캐시를 조회하고, 캐시에 데이터가 없는 경우 DB에서 조회하여 캐시에 저장합니다.
  - 지연 로딩(lazy-loading)캐싱 방식으로, 필요한 경우에만 데이터 소스에서 데이터를 가져옵니다.
- `@CachePut` : 캐시 저장만 하는 어노테이션 - `Write-through`
  - @Cacheable과 유사하게 캐시에 저장하지만, 조회 시 저장된 캐시의 내용을 사용하지 않고 항상 DB에서 조회.
  - Write-through 캐싱 전략은 데이터가 변경될때마다 캐시와 데이터 소스가 동시에 업데이트 됩니다.
  - 항상 캐시 데이터가 최신 상태를 유지할 수 있도록 보장합니다.
- `@CacheEvict` : 캐시 제거를 위한 어노테이션  - `Cache Invalidation`
  - 일정한 주기로 캐시를 제거하거나 값이 변할때 캐시를 제거.
  - Cache Invalidation 전략은 데이터 소스의 데이터가 변경될 때 캐시를 무효화하거나 삭제하여 캐시의 데이터가 최신 상태를 유지하도록 합니다.
- `@Caching` : 여러 캐시 연산을 결합하여 사용할 수 있는 어노테이션
  - 여러 캐시 연산을 하나의 메서드에 적용하여 복잡한 캐싱 시나리오 시 사용 가능합니다.

2024-05-16 00:23 UTC, codesejin commented on src/test/java/com/flab/offcoupon/AbstractIntegrationContainerBaseTest.java
넵 주석으로 달아놓겠습니다 감사합니다~!

2024-05-16 00:23 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @CsvSource(value = {"10000, 0", "50000, 0"})
감사합니다!

2024-05-21 01:42 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/entity/OrderCouponTest.java
> +    }
넵 길더라도 명시적으로 표시하는걸로 DisplayName 수정했습니다!

2024-05-21 02:31 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/entity/OrderDetailTest.java
> +}
기존 코드에는 생성자에 validation이 없었지만, validation을 추가해서 실패/엣지 케이스를 추가했습니다.

- 성공케이스: 개발자가 생각한 해피케이스를 그대로 작성
- 실패케이스: 비즈니스 로직상 실패하거나, 불가능한 값을 넣는 경우 등 명확한 실패 지점으로 케이스
- 엣지케이스: 성공과 실패가 나뉘는 경계에 대한 테스트. 예를 들어, Positive라는 객체 생성에 대한 테스트를 한다면 '0' 이라는 값으로 생성할 때 성공할지 실패할지에 대한 테스트.

2024-05-21 03:05 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @DisplayName("[SUCCESS] 세일 가격이 0보다 클 경우 세일 가격 반환")
`세일가격이 0보다 작은 값이 들어올 경우`는 DB조회시 바로 생성자에 매핑되기 때문에 `음수 validation의 경우` 생성자 테스트로 분리해서 작성하는걸로 변경했습니다!

2024-05-21 03:30 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/entity/ProductTest.java
> +        @DisplayName("[SUCCESS] 상품 가격에 수량을 곱한 값을 반환")
알려주신대로 테스트 목적을 알 수 있게끔 @DisplayName의 설명을 명확하게 변경했습니다!

2024-05-21 03:52 UTC, codesejin commented on src/test/java/com/flab/offcoupon/domain/redis/EventRedisEntityTest.java
> +            assertEquals(dailyIssueEndTime, eventRedisEntity.dailyIssueEndTime());
말씀해주신대로`assertAll` 과 람다 표현식을 사용해서 각 단언문이 개별적으로 실행되고, 하나의 단언문이 실패하더라도 다른 단언문 모두 실행되도록 변경했습니다!

2024-05-21 10:20 UTC, codesejin commented on src/test/java/com/flab/offcoupon/AbstractIntegrationContainerBaseTest.java
> +@ActiveProfiles("local")
@ContextConfiguration를 제외하곤 알고 있는 어노테이션인데요!  테스트 컨테이너 라이브러리가 제대로 안되서 추가했던 어노테이션입니다. 통합테스틑 컨테이너가 아닌 테스트 DB를 사용하는걸로 결정했습니다.
테스트 시 ci를 컨테이너화해서 실행한다면 빌드 속도가 느려지기 때문입니다!

`@SpringBootTest`
 : 스프링 부트 애플리케이션을 통합 테스트하기 위한 어노테이션입니다. 스프링 컨텍스트 전체를 로드해서 실제 애플리케이션과 유사한 환경에서 테스트를 진행합니다.
 
 `@Testcontainers`
 : 테스트컨테이너 라이브러리를 사용해서 컨테이너화 된 데이터베이스나 다른 의존성을 테스트 중에 실행할 수 있도록 지원합니다.
 
 `@AutoConfigureTestDatabase `
 : 테스트 중에 사용될 데이터베이스 설정으로 자동으로 구성할 수 있도록 합니다.

`@ActiveProfiles` 
: 특정 프로파일을 테스트 실행히 사용할때 설정합니다.

2024-05-21 11:57 UTC, f-lab-maverick approved these changes
상당히 많은 테스트를 잘 작성해주셨습니다.
이제 테스트코드 작성도 꽤나 많이 익숙해지셨네요 👍 👍 

객체지향적인 코드로 테스트 관점을 DB / Service 레이어가 아닌 도메인 객체로 이동하는 것을 연습하셨는데요, 이 PR에서 배운 부분을 잘 발전시켜주시면 좋겠습니다. 이 방식으로 테스트해보셔서 알겠지만 테스트하기 좋은 코드를 만드는 것에 꽤나 효과적이기 때문에 단위테스트를 만드신다면 현재와 같은 방식이 있다는 것을 기억해주세요.

물론 객체지향적인 코드가 만능은 아닙니다. 작성해보시면서 단점이라고 느껴지셨던 부분이 있으셨다면 코멘트로 남겨주세요.

2024-05-21 11:57 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/entity/OrderDetail.java
> +    private void validateIdIsNegativeAndPricePerEachIsNegative(long productId, long quantity, BigDecimal pricePerEach) {
메서드 이름을 보면 ID와 가격이 음수인 것을 검증하는 것으로 보일 여지가 있네요~ 메서드 명을 수정하는게 좋아보입니다. 또한, 파라미터를 3개 받고 있지만 실질적으로는 모두 동일한 양수 여부를 확인하는 로직이므로, 아래와 같이 변경도 가능합니다.

메서드 명은 "무엇을 하는가"를 나타내는 것이 좋지만, 이 메서드처럼 복합적인 역할을 하는 메서드의 경우에는 "비즈니스 로직"을 메서드로 표현할 수 있으면 좋습니다. 

```
verifyPositiveNumber(Long number) {
  new PositiveLong(number);
}

verifyPositiveNumber(BigDecimal number) {
  new PositiveDecimal;
}

...
verifyPositiveNumber(productId);
verifyPositiveNumber(quantity);
verifyPositiveNumber(pricePerEach); // 생성자에 BigDecimal을 받는 `PositiveDecimal`을 생성해도 좋다.
```

2024-05-21 11:57 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/entity/helper/AppliedCouponInfo.java
> +    }
`discountAmount.compareTo(BigDecimal.ZERO) <= 0` 의 형태 대신 `Negative` 라는 래핑 클래스도 고려해보면 좋겠네요.
`positiveLongCouponId.getValue() > 0`은 이미 검증된 항목이므로 삭제하시는건 어떨까요?

2024-05-21 11:57 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/model/PositiveBigDecimal.java
> +    }
컬랙선을 만들기 위한 Inner Class가 필요한가요?
단순하게 아래와 같이 작성도 가능해서 굳이 필요하지 않아 보입니다. 클래스레벨에서 너무 많은 기능을 제공하려 하지 않아도 됩니다~
```
values.stream.map(PositiveBigDecimal::new).toList()
```

2024-05-21 11:57 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/service/coupon_issue/sync/LettuceLockCouponIssueTest.java
> +    @Transactional
`@Transactional`이 중복으로 들어있네요~ 클래스레벨에 선언되어있으므로 제거해도 무방해보입니다.

2024-05-21 11:57 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/service/coupon_issue/sync/PessimisticLockCouponIssueTest.java
> +    @Transactional
여기도 중복으로 `@Transactional`이 선언되었습니다.

2024-06-01 08:37 UTC, codesejin commented on src/main/java/com/flab/offcoupon/model/PositiveBigDecimal.java
> +    }
오! stream을 사용하면 간단하게 처리 가능하군요 알려주셔서 너무 감사합니다!

2024-06-02 14:56 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/entity/helper/AppliedCouponInfo.java
> +    }
넵 추가적으로 래핑클래스 추가해서 수정했습니다!

2024-06-02 14:58 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/entity/OrderDetail.java
> +    private void validateIdIsNegativeAndPricePerEachIsNegative(long productId, long quantity, BigDecimal pricePerEach) {
슬랙으로 여쭤본 내용 기반과 함께 생성자 내부에서 이미 음수 체크를 하기 때문에 별도로 메소드로 분리하지 않아도 된다고 판단했습니다! 따라서 아래처럼 수정했습니다!

```java
	private OrderDetail(OrderInfo orderInfo, TimeParams timeParams) {
		this.productId = new PositiveLong(orderInfo.getProductId()).getValue();
		this.quantity = new PositiveLong(orderInfo.getQuantity()).getValue();
		this.pricePerEach = new PositiveBigDecimal(orderInfo.getPricePerEach()).getValue();
		this.totalOrderPrice = orderInfo.getTotalOrderPrice();
		this.totalDiscountPrice = orderInfo.getTotalDiscountPrice();
		this.totalPaymentPrice = orderInfo.getTotalPaymentPrice();
		this.createdAt = timeParams.createdAt();
		this.updatedAt = timeParams.updatedAt();
	}
```

2024-06-02 15:15 UTC, codesejin commented on src/test/java/com/flab/offcoupon/service/coupon_issue/sync/LettuceLockCouponIssueTest.java
> +    @Transactional
넵 알려주셔서 감사합니다 ~!

2024-06-02 15:15 UTC, codesejin commented on src/test/java/com/flab/offcoupon/service/coupon_issue/sync/PessimisticLockCouponIssueTest.java
> +    @Transactional
넵 알려주셔서 감사합니다 ~!

2024-06-03 12:31 UTC, codesejin commented
도메인 객체로 단위테스트 작성
- 장점 : 
  - 더 작은 범위의 단위 테스트를 작성할 수 있기 때문에, 기존 통합테스트가 많았던 것에 비해 CI속도가 개선됩니다.
  -  TDD방식으로 테스트하기 좋습니다.
- 단점 :   
  - 처음부터 도메인 객체를 작게 분할하지 않을 경우 변경 범위가 많아집니다.
  -  작은 단위의 도메인 객체를 사용하기 위해 getter 사용빈도가 많아져서 클래스간 결합도가 높아지는것 같습니다.ㅋ
  - 예를 들어, OOP에서 객체들간의 협력을 하기 위해 getter를 사용하는 대신 TDA방식을 사용해야 함을 권장하는데, 이부분이 미흡한것 같습니다.
  
현재로서는 음수/양수 체크용도로만 도메인 객체를 이용했는데, 더 다양하고 자세한 도메인으로 쪼개는 방법에 대해 공부하면 좋을것 같습니다.

2024-06-10 12:08 UTC, merged