[#3] 로그인 기능 구현
f-lab-edu/off-coupon pull request #5
Opened 2024-02-10 11:57 UTC by codesejin

- 관련 Issue : #3 

- [x] Redis Config 설정 (session storage)
- [x] 로그인 기능 구현
---

관련해서 진행할 기능
1. 로그인 기능 slice test ( controller, service, repository )
2. spring security 필터 구현
3. 이벤트 등록 및 쿠폰 발행은 사용자가 아닌 `관리자`가 해야 하므로 ROLE 추가

---
<img width="1051" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/35552ed5-2646-4a51-b194-01bf51c90465">

2024-02-11 15:45 UTC, f-lab-maverick requested changes
고생하셨습니다. 리뷰 확인해주시고 연휴 끝나고 나머지 부분 마무리해서 다시 리뷰 요청해주세요~

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/config/RedisConfig.java
> +        redisTemplate.setHashValueSerializer(new StringRedisSerializer());
RedisTemplate에 설정할 수 있는 Serializer는 어떤 구현체가 있으며, 그 구현체들은 어떤 특징을 가지고있는지 정리해보시겠어요? 일반적으로 `StringRedisSerializer`가 핸즈온 가이드로 많이 나와있어서 많이 사용하는데요, 이런 전역 설정은 한줄한줄이 정말 큰 역할을 하기 떄문에 설정 하나하나가 어떤 영향을 끼치는지 알아보면 좋겠습니다~

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/config/RedisConfig.java
> +        RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
`RedisConnectionFactory `는 어떤 종류의 구현체가 있을까요? `LettuceConnectionFactory`를 왜 선택하셨나요?

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/controller/MemberController.java
> +        sessionManager.setLoginMember(loginMember.getId());
Spring Security를 쓰면 인증과 인가에 관한 부분을 이렇게 직접 컨트롤러로 구현하지 않아도 구현이 가능합니다.
`UserDetailService`, `Spring Security Filter Chain`등을 키워드로 검색해보시면 어떻게 로그인을 구현할 수 있는지 찾아보실 수 있을거에요.

이렇게 직접적으로 로그인을 구현하게되면 Spring Security로 설정가능한 `AuthenticationSuccessHandler`, `authenticationfailurehandler`등을 사용할 수 없으며, 인증과 인가에 관련한 설정도 사용하기 어렵습니다.

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/dto/request/LoginMemberRequestDto.java
> +    private final String password;
일반적으로 로그인을 검증할 때에는 입력된 패스워드에 대해서 유효성검증을 하지 않습니다.
왜냐하면, 패스워드 유효성 로직은 계속해서 변화하며 만약 정책 변경 이전 패스워드로 DB에 저장된 상태라면 이 유효성검증 정책으로 인해 로그인할 수 없기 때문입니다~

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/exception/GlobalExceptionHandler.java
> +    }
이 예외의 경우 전역 예외 핸들러로 처리할 이유가 있을까요?
패스워드의 검증은 회원가입 또는 비밀번호 변경 기능정도에서만 사용되지 않을까요?

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/MemberService.java
> +        validatePassword(loginMemberRequestDto.getPassword(), member.getPassword());
`validate`는 검증을 한다는 뜻인데요, 유효성에 대한 검증인지 데이터가 일치하는지에 대한 검증인지가 애모호해보입니다. 두가지 방법이 있을 것으로 보입니다. 더 좋은 아이디어가 없을지 한번 고민해보세요.
1. 메서드 이름 변경
`isPasswordMatched(..., ...)`
2. `Member` 클래스로 메서드 이동
조금 더 객체지향 + 도메인 지향적인 방식입니다. password에 getter를 아예 제거해버림으로써 password 데이터를 객체에서 꺼낼 수 없게 만듭니다.

패스워드 데이터는 일치하는지 여부만 확인하기 때문에 getter를 제거해도 됩니다.
```
class Member {
...
  public boolean matchPassword(final String encrypedPassword) {
  
  }
}

member.matchPassword(...);
```

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/MemberService.java
> +    public Member findMemberByEmail(String email) {
`Propagation.MANDATORY`를 설정하신 이유가 있으실까요?

2024-02-11 15:45 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/util/SessionManager.java
> +public class SessionManager {
Spring Security의 기본 설정은 세션을 사용하도록 되어있습니다. 이러한 설정또한 자동으로 해주니 확인해보세요~

2024-02-18 02:57 UTC, codesejin commented on src/main/java/com/flab/offcoupon/config/RedisConfig.java
> +        redisTemplate.setHashValueSerializer(new StringRedisSerializer());
[Spring Data Redis 공식문서](https://docs.spring.io/spring-data/redis/reference/redis/template.html)에 따르면 org.springframework.data.redis.serializer 패키지에는 2가지의 직렬화 프로세스가 있습니다.
- RedisSerializer를 기반으로 한 양방향 직렬화
  -  주로 byte[]로 직렬화
- RedisElementReader 및 RedisElementWriter를 사용하는 Element readers 와 writers
  - ByteBuffer를 사용

기본적으로 RedisCache 및 RedisTemplate에서 기본적으로 사용되는건 `JdkSerializationRedisSerializer`와 `StringRedisSerializer`입니다.

하지만 객체 매핑과 Json형식으로 데이터를 저장하기 위해 `Jackson2JsonRedisSerializer` 또는 `GenericJackson2JsonRedisSerializer` 을 사용합니다.

---
[RedisTemplate의 공식문서](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html)
- setDefaultSerializer : 기본적으로 사용할 직렬화, 기본이 JdkSerializationRedisSerializer
- setKeySerializer : Redis의 `단일 키(혹은 단순한 값)`를 직렬화
- setValueSerializer : Redis의 `단일 값(문자열, 객체 등)`를 직렬화
- setHashKeySerializer : Redis `해시의 키`를 직렬화
- setHashValueSerializer : Redis `해시의 값(필드에 대응하는 값)`를 직렬화

security context에 저장된 Authentication의 경우 Hash타입으로 저장되기 때문에 `setHashKeySerializer`와 `setHashValueSerializer`를 사용하겠습니다.
![image](https://github.com/f-lab-edu/off-coupon/assets/101460733/101727ba-06ab-49cc-98f8-f8e128a0acdc)

---
- JdkSerializationRedisSerializer : 디폴트로 등록되어있는 Serializer
- StringRedisSerializer : String타입을 읽어서 저장하지만, 엔티티나 DTO같은 타입은 Casting이 안된다.
- Jackson2JsonRedisSerializer : classType 값을 json 형태로 저장한다.
- GenericJackson2JsonRedisSerializer : 모든 classType을 json 형태로 저장할 수 있는 범용적인 Jackson2JsonRedisSerializer이지만, 해당 class의 기본 생성자가 꼭 필요하다.

2024-02-18 03:09 UTC, codesejin commented on src/main/java/com/flab/offcoupon/config/RedisConfig.java
> +        RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
[Spring Data Redis ](https://spring.io/projects/spring-data-redis)에서는 RedisConnectionFactory 인터페이스를 구현한 구현체로 `JedisConnectionFactory` 와 `LettuceConnectionFactory` 클래스를 기본으로 제공합니다. 

[redis 공식 문서에서 말하는 Lettuce와 Jedis](https://redis.com/blog/jedis-vs-lettuce-an-exploration/)

- Lettuce 
  -  Non-blocking인 Redis 자바 클라이언트
  - 동기식과 비동기식 통신 모두 지원
  - Cluster, Sentinel, Pipelining, codecs을 지원하는고급 클라이언트

- Jedis
  - Redis 내부 클라이언트 라이브러리로 성능과 사용 편의성 강조
  - 다른 Redis Java 클라이언트에 비해 가볍고 적은 기능을 제공하지만 대량의 메모리 처리 가능
  - 클러스터와 동기적으로만 작동
  
  
  Jedis를 사용한다면 동기적인 연결만 지원하기에 트래픽이 몰리느 상황에서 병목을 발생시킬 수 있고, Redis의 클러스터 모드를 지원하지 않기 때문에 나중에 session storage가 아닌 클러스터로 변경하게 되었을 경우 적합하지 않습니다.
 그래서 비동기 논 블로킹으로 대량의 트래픽을 처리할 수 있는 Lettuce를 선택했습니다.

2024-02-18 03:10 UTC, codesejin commented on src/main/java/com/flab/offcoupon/dto/request/LoginMemberRequestDto.java
> +    private final String password;
정책 변경을 생각하지 못했습니다. 알려주셔서 감사합니다~

2024-02-18 03:11 UTC, codesejin commented on src/main/java/com/flab/offcoupon/controller/MemberController.java
> +        sessionManager.setLoginMember(loginMember.getId());
AuthenticationSuccessHandler, authenticationfailurehandler, 인증과 인가를 처리할 수 있도록 formlogin으로 변경했습니다~

2024-02-18 03:12 UTC, codesejin commented on src/main/java/com/flab/offcoupon/exception/GlobalExceptionHandler.java
> +    }
맞습니다 전역 예외 핸들러라는걸 생각하지 못하고 추가했습니다. 감사합니다!

2024-02-18 03:26 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/MemberService.java
> +        validatePassword(loginMemberRequestDto.getPassword(), member.getPassword());
메소드명 지을때 애매하게 짓는 습관을 신경써야겠네요..!

- 유효성에 대한 검증인지
- 데이터가 일치하는지에 대한 검증인지

---

2번째 getter를 제거하고 TDA(tell don't ask)원칙을 적용하려고 했지만, Spring Security 중 UserDetails만드는 곳에서 get메소드르르 사용해서 인증객체를 생성하기 때문에 getter제거는 하지 못했습니다! 

<img width="832" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/472ca00c-e9f3-4e55-848f-223ff3bf66c7">

하지만 일부 필드에만 getter를 사용할 경우에는 객체지향 + 도메인 지향적인 방식으로 적용해야 한다는 것은 이해했습니다!

2024-02-18 06:14 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/MemberService.java
> +    public Member findMemberByEmail(String email) {
적용하지 않았을때 sonarcloud에서 이슈사항으로 잡혀서 적용했던 내용입니다!

MANDATORY는 활성화된 트랜잭션이 있으면 해당 트랜잭션에 참여하고,  활성화된 트랜잭션이 없으면 예외를 발생시킵니다.  
SELECT를 할뿐인데 트랜잭션을 의무적으로 설정해놨던건 실수였던것 같습니다. 지우겠습니다

2024-02-18 11:46 UTC, f-lab-maverick requested changes
기능적인 부분은 거의 완성되었지만, 테스트쪽에서 아직 좀 더 확인해야할 사항이 보입니다. 이 부분은 큰 변경사항이 아니니 반영해주시면 빠르게 다시 리뷰 진행하겠습니다. 다시 확인 부탁드려요~

2024-02-18 11:46 UTC, f-lab-maverick commented on build.gradle
> +    testImplementation 'junit:junit:4.13.1'
JUnit 4버전을 사용하시는 이유가 있나요?
Spring boot 최신버전에는 jUnit 5버전이 기본적으로 탑재되어있습니다.

2024-02-18 11:46 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/controller/HomeController.java
> +    }
테스트를 위해 만들어둔 API는 삭제해주세요~

2024-02-18 11:46 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/dto/response/SignupMemberResponseDto.java
> +    }
이런 단순한 생성자는 `@RequiredArgsConstructor`를 사용해서 단순화해주는것이 관습적인 코드를 줄일 수 있는 방법중 하나입니다

2024-02-18 11:46 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/dto/response/SignupMemberResponseDto.java
> +    }
정적 팩토리 메서드 패턴을 사용하더라도, 그저 파라미터가 엔티티이고 별도 비즈니스로직이 없는 경우라면 정적 팩토리 메서드를 사용하는 의미가 크지 않습니다. 이런 경우에는 `Member`를 파라미터로 받는 public 생성자를 만들어주는것이 객체 생성을 명확하게 명시할 수 있는 방법입니다.

2024-02-18 11:46 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/security/SecurityTest.java
> +import org.springframework.test.context.junit4.SpringRunner;
Junit 4를 사용하고계시네요. 이러면 JUnit5엔진과 JUnit4 엔진이 같이 돌아가게 됩니다. 동작은 하겠지만, 이렇게 만들 필요가 없는게 JUnit5에서는 4의 기능을 대부분 지원해줍니다.

아마 `@RunWith(SpringRunner.class)` 문을 사용하시려고 하신듯 한데요, jUnit5에서는 `@SpringBootTest`어노테이션이 있으면 저 구문을 사용하지 않아도 됩니다.

2024-02-18 11:46 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/security/SecurityTest.java
> +//    }
실패하는 테스트는 해결방법을 찾아서 꼭 해결해서 구현해주세요

2024-02-18 11:46 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/service/MemberServiceTest.java
> +//    }
이 부분도 해결이 안된것으로 보입니다~ 불필요한 테스트라면 삭제해주시고, 필요한 테스트라면 구현해주세요

2024-02-19 03:48 UTC, codesejin reviewed
리뷰 주신 사항 반영해서 새로 push 완료했습니다..!

2024-02-19 03:48 UTC, codesejin commented on src/main/java/com/flab/offcoupon/dto/response/SignupMemberResponseDto.java
> +    }
수정했습니다!

2024-02-19 03:48 UTC, codesejin commented on src/test/java/com/flab/offcoupon/security/SecurityTest.java
> +//    }
넵 구현되도록 수정했습니다!

2024-02-19 03:48 UTC, codesejin commented on src/test/java/com/flab/offcoupon/service/MemberServiceTest.java
> +//    }
이부분은 따로 필요없을 것 같아서 제거했습니다!

2024-02-19 03:48 UTC, codesejin commented on src/test/java/com/flab/offcoupon/security/SecurityTest.java
> +import org.springframework.test.context.junit4.SpringRunner;
알려주셔서 감사합니당...!

2024-02-19 03:48 UTC, codesejin commented on src/main/java/com/flab/offcoupon/dto/response/SignupMemberResponseDto.java
> +    }
정적 팩토리 메서드를 사용할때 비즈니스 로직과 관련이 있어야 하는군요..관련해서 좀 더 알아보겠습니다..!

2024-02-19 03:48 UTC, codesejin commented on build.gradle
> +    testImplementation 'junit:junit:4.13.1'
@RunWith 임포트할때 다운받아진것같습니다.. 아래 리뷰해주신대로 수정했습니다!

2024-02-19 22:58 UTC, f-lab-maverick approved these changes
고생하셨습니다. 로그인 기능 구현을 완료하신걸 축하드려요~
머지해주셔도 좋습니다.

2024-02-20 02:29 UTC, merged