[#7] 쿠폰 발급 기능 구현
f-lab-edu/off-coupon pull request #8
Opened 2024-03-07 09:53 UTC by codesejin

- 관련 Issue : https://github.com/f-lab-edu/off-coupon/issues/7

# 쿠폰 발급 기능 API
![image](https://github.com/f-lab-edu/off-coupon/assets/101460733/a0c1bc97-a33f-47e1-840f-cf119935c85f)

- [x] 다양한 락 기법 적용(비관적 락, 네임드락, lettuce 락, redisson락)
- [x] Redis Cache 적용

----

# TODO

1. 락을 통해서 정합성을 맞춰졌지만, 처리량은 낮아서 비동기식으로 처리해야 합니다.
참고할 사이트 : [올리브영 테크블로그](https://oliveyoung.tech/blog/2023-08-07/async-process-of-coupon-issuance-using-redis/)
3. 테스트 코드 작성 미흡해서 추가해야합니다.

2024-03-09 01:32 UTC, f-lab-maverick requested changes
Lock을 추상화하고 이를 구조적으로 만드셨군요 👍
조금만 다듬고, 테스트케이스를 추가하면 될정도로 완성도 높은 개발이 보이네요. 우선 이 PR에서는 제가 리뷰드린정도로만 수정하도록 하고, 이후 스탭으로 아래 두가지를 진행해보시죠

1. 성능을 개선할 방법은 없는가?
2. 테스트 코드는 충분한가?

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/component/DistributeLockExecutorWithLettuce.java
> +            // Spin Lock: 100밀리초 동안 계속해서 락을 시도합니다.
주석과 코드의 동작이 일치하지 않습니다.
100 밀리초 간격으로 락 획득을 시도하는것 아닐까요?

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/component/DistributeLockExecutorWithNamedLock.java
> +            throw new IllegalStateException("NamedLock 락 반납 실패 [ " + lockName + " ]");
모종의 이유로 락 반납에 실패했다면, 해제되지 않은 락은 어떻게될까요?

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/config/redis/SessionConfig.java
> +//    private String redisPassword;
사용하지 않는 코드라면 주석으로 남기지 마시고 깔끔하게 삭제해주세요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/controller/CouponIssueController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(couponIssueRequestService.syncIssueCoupon(currentDateTime, eventId, couponId, memberId));
날짜 하드코딩 제거해주세요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +    }
날짜 없이 시간만으로 범위를 계산하는 것은 비즈니스로직적으로 버그가 발생하기 쉽습니다. 날짜를 포함하여 계산해보시겠어요?

예를들어, 발급가능한 시간이 21:00 ~ 03:00이라면 이 로직이 바로 깨져버리지 않을까요?

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +    }
시간을 다루는 클래스는 `java.time.*` 패키지에 존재합니다.
`Duration`, `Period`등 시간을 다루기 위한 클래스가 존재하니 확인해보세요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +        if (!availableIssueTime(localDateTime)) {
`if (!availableIssueDate(localDateTime))` 조건이 반복되어 사용되고있습니다. 중복된 체크 아닐까요?

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/repository/redis/LettuceLockRepository.java
> +    }
현재는 락을 거는 대상이 하나이기때문에 long type으로 키를 생성하시는데요, 이후 락을 거는 대상이 늘어난다면 prefix를 추가해주는 형식으로 lock format이 필요할 것으로 보이네요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/couponIssue/async/AsyncCouponIssueService.java
> +        distributeLockExecutorWithRedisson.execute("redisson_lock" + couponId, 3000, 3000, () -> {
`3000`과 같은 매직넘버는 상수로 관리해주세요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/couponIssue/sync/DefaultCouponIssueService.java
> +    }
DefaultCouponIssueService  내부에서만 사용하는 로직이라면 `private` 접근제어자로 설정해주세요~

2024-03-09 01:32 UTC, f-lab-maverick commented on src/test/java/com/flab/offcoupon/service/DefaultCouponIssueServiceTest.java
> +//    }
주석으로 처리하지 말고, 사용하지 않거나 완성되지 않은 코드는 삭제해주세요~

2024-03-09 01:33 UTC, f-lab-maverick commented
추가적으로 SonarCloud에서 발견된 코드 관련 개선점도 적용해보세요~

2024-03-11 04:19 UTC, codesejin commented on src/main/java/com/flab/offcoupon/component/DistributeLockExecutorWithLettuce.java
> +            // Spin Lock: 100밀리초 동안 계속해서 락을 시도합니다.
맞습니다! `락 획득을 시도합니다` 로 변경하겠습니다!

2024-03-11 04:30 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +        if (!availableIssueTime(localDateTime)) {
첫번째 조건문은 날짜를 검증하는 용도이고, 두번째 조건문은 시간을 검증하는 용도입니다! 
날짜와 시간 별도의 메소드로 검증하도록 해놨기 때문에 중복은 아니라고 생각합니다!

2024-03-11 04:31 UTC, codesejin commented on src/main/java/com/flab/offcoupon/component/DistributeLockExecutorWithNamedLock.java
> +            throw new IllegalStateException("NamedLock 락 반납 실패 [ " + lockName + " ]");
해당 코드에서 락 반납에 실패하는 경우, 락은 여전히 획득 상태로 남게 됩니다. 락이 정상적으로 반납되지 않으면 다른 프로세스나 스레드에서 해당 락을 획득하기 어려워질 수 있고, 이로 인해 `데드락`이 발생할 수 있습니다.

만일 락 반납을 시도해도 0 또는 null이 나올 경우, 예외 처리나 로깅을 통해 개발자가 알 수 있도록 처리해야 합니다.

2024-03-11 05:31 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/couponIssue/sync/DefaultCouponIssueService.java
> +    }
이부분도 `캡슐화` 때문에 private으로 할지 고민했었는데,  접근제어자를 `private` 으로 설정하면 스프링에서 트랜잭션 기능이 동작하지 않습니다! 
<img width="1248" alt="image" src="https://github.com/f-lab-edu/off-coupon/assets/101460733/e2d89e72-6806-441f-ab0e-a77987938d38">
[스프링 공식문서의 Transaction Manager](https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/transaction.html)를 확인해보면 `public`visibility에만 트랜잭션이 적용 가능하다고 합니다!

2024-03-11 07:03 UTC, codesejin commented on src/test/java/com/flab/offcoupon/service/DefaultCouponIssueServiceTest.java
> +//    }
주석 풀었습니다!

2024-03-11 07:09 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/couponIssue/async/AsyncCouponIssueService.java
> +        distributeLockExecutorWithRedisson.execute("redisson_lock" + couponId, 3000, 3000, () -> {
매직넘버로 수정했습니다~

2024-03-11 07:15 UTC, codesejin commented on src/main/java/com/flab/offcoupon/repository/redis/LettuceLockRepository.java
> +    }
```
    private String generateKey(Long key, String prefix) {
        return prefix + key.toString();
    }
```

로 수정하겠습니다~

2024-03-11 07:16 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +    }
`날짜 없이 시간만으로 범위를 계산하는 것은 비즈니스로직적으로 버그가 발생하기 쉽습니다. 날짜를 포함하여 계산해보시겠어요?`
해당 리뷰에 대한 내용은 이벤트 날짜랑 시간을 별도의 메소드로 서로 분리해서 검증하도록 해놨는데, 같이 해야되는걸까요??
availableIssueDate() -> 날짜
availableIssueTime() -> 시간

2024-03-11 07:17 UTC, codesejin commented on src/main/java/com/flab/offcoupon/controller/CouponIssueController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(couponIssueRequestService.syncIssueCoupon(currentDateTime, eventId, couponId, memberId));
넵 LocalDateTime.now()로 변경했습니다

2024-03-11 09:00 UTC, codesejin commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +    }
시간을 다루기 위해 Duration 클래스를 사용하고, 기간을 다루기 위해 Period클래스를 사용하도록 수정했습니다!

2024-03-13 12:45 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/couponIssue/sync/DefaultCouponIssueService.java
> +    }
이부분은 멘토링때 얘기해주신 대로 하위메소드에는 @Transactional 제거하고, 외부클래스에서 사용하지 않는 메소드는 private으로 변경했습니다!
- 상위메소드에 트랜잭션이 있기 때문에 논리적으로 연결됨

2024-03-13 12:46 UTC, codesejin commented on src/main/java/com/flab/offcoupon/config/redis/SessionConfig.java
> +//    private String redisPassword;
넵 Lettuce랑 Redisson이랑 전부 사용할 수 있도록 해서 반영했습니답

2024-03-13 13:36 UTC, codesejin commented
> 추가적으로 SonarCloud에서 발견된 코드 관련 개선점도 적용해보세요~

2024-03-15 07:06 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +    }
날짜와 시간이 묶여서 계산되어야 하는 경우가 있기 때문에 "기간"이라는 로직을 다룰 때 주의해야합니다~ 이 부분 유의해주시면 되겠습니다

2024-03-15 07:07 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/domain/redis/EventRedisEntity.java
> +        if (!availableIssueTime(localDateTime)) {
메서드 명이 달랐군요~ 제가 잘못본거같습니다 :)

2024-03-15 07:51 UTC, f-lab-maverick approved these changes
고생하셨습니다~ 머지해주셔도 좋습니다.

2024-03-15 07:51 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/cache/CouponCacheService.java
> +    }
cache service내부에서만 사용하는거라면 private 접근제어자를 사용해주세요~ 
외부에 제공하지 않는 용도의 메서드인데, public 접근제어자로 두면 개발하다가 실수로 사용할 수 있으니 아예 가능성을 닫아두는게 좋습니다.

2024-03-15 07:51 UTC, f-lab-maverick commented on src/main/java/com/flab/offcoupon/service/cache/EventCacheService.java
> +    }
이 부분도 불필요하게 접근제어를 열어주지 않는것이 좋겠네요

2024-03-15 12:39 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/cache/CouponCacheService.java
> +    }
넵 이부분을 계속 놓치고 있네요! 다음 pr때는 신경써보겠습니다!

2024-03-15 12:39 UTC, codesejin commented on src/main/java/com/flab/offcoupon/service/cache/EventCacheService.java
> +    }
넵 수정하겠습니다 감사합니다~

2024-03-15 12:41 UTC, merged